name: hotfix-main-PR
# Controls when the workflow will run
on:
  pull_request_target:
    types:
      - closed
    branches:
      - 'hotfix-**'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "PR title is ${{ github.event.pull_request.title }}"
        echo "PR number is ${{ github.event.pull_request.number }}"
        commit_sha=${{ github.event.pull_request.head.sha }}
        target_branch=$GITHUB_REF
        requested_branch=$GITHUB_HEAD_REF
        echo "PR requested  Branch name  : $requested_branch"
        echo "The author of this PR is: ${{ github.event.pull_request.user.login }}"
        target_branch=$(basename "$target_branch")
        hotfix_tag=$(echo "$target_branch" | cut -d '-' -f 2)
        trim_sha="${commit_sha:0:7}"
        echo "The target branch name: $target_branch and hotfix_tag is $hotfix_tag"
        echo "Merge commit is $trim_sha"
        final_branch="$hotfix_tag-$trim_sha"
        echo "repo url is $GITHUB_REPOSITORY"
        gh repo clone $GITHUB_REPOSITORY
        repo_name=$(echo $GITHUB_REPOSITORY | awk -F ["/"] '{print $2}')
        git config --global user.email "${GIT_CONFIG_EMAIL}" && git config --global user.name "${GIT_CONFIG_NAME}"
        cd $repo_name
        ls
        git checkout -b final_branch main
        git cherry-pick $commit_sha
      env:
        GH_TOKEN: ${{ github.token }}
        GIT_CONFIG_NAME: ${{ secrets.GIT_TARGET_USERNAME }}
        GIT_CONFIG_EMAIL: ${{ secrets.GIT_TARGET_EMAIL }}
