name: hotfix-main-PR
# Controls when the workflow will run
on:
  pull_request_target:
    types:
      - closed
    branches:
      - 'hotfix-**'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "PR title is ${{ github.event.pull_request.title }}"
        echo "PR number is ${{ github.event.pull_request.number }}"
        commit_sha = "echo ${{ github.event.pull_request.head.sha }}"
        target_branch="echo $GITHUB_REF"
        requested_branch="echo $GITHUB_HEAD_REF"
        echo "The target branch name : $target_branch"
        echo "Merge commit is $commit_sha"
        echo "PR requested  Branch name  : $requested_branch"
        echo "The author of this PR is: ${{ github.event.pull_request.user.login }}"

